apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-controller
      image: nginx
      resources:
        requests:
          cpu: '500m'
          memory: '128mi'
        limits:
          cpu: none
          memory: '128mi'
